
excluded: 
  - Pods
  - Cartelerapp/AppDelegate.swift
  - Cartelerapp/SceneDelegate.swift

line_length: 
  ignores_comments: true

disabled_rules: # rule identifiers to exclude from running
  - identifier_name